version: "3.5"

services:
  nginx:
    image: nginx:latest
    container_name: lemp_nginx
    restart: always
    ports:
      - "${MAGENTO_HTTP_PORT}:80"
      - "${MAGENTO_HTTPS_PORT}:443"
    volumes:
      - "./config/nginx/:/etc/nginx/conf.d/:rw"
      - "./config/mkcert:/etc/nginx/mkcert:rw"
      - "${ROOT_FOLDER}:/var/www/:rw"

  php:
    container_name: lemp_php
    restart: always
    build:
      context: ./build
      dockerfile: php.Dockerfile
    environment:
      USERNAME: "${USER}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./config/nginx/:/etc/nginx/conf.d/"
      - "./config/mkcert:/etc/nginx/mkcert"
      - "${ROOT_FOLDER}:/var/www/:rw"

  mysql:
    image: mysql:8.0
    container_name: lemp_mysql
    platform: linux/x86_64
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "mysql:/var/lib/mysql"
      - "./config/mysql/:/etc/mysql/conf.d"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lemp_phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: "2G"
      MEMORY_LIMIT: "2G"

  # kibana:
  #   image: kibana:7.9.3
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - 5601:5601
  elasticsearch:
    image: elasticsearch:7.9.3
    container_name: lemp_elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - "elasticsearch:/usr/share/elasticsearch/data/"

volumes:
  mysql:
  elasticsearch:
